version: 0.2

phases:
  build:
    commands:
      - echo "Construyendo aplicación"
      - echo "<html><body><h1>Ciclo CICD Completo</h1></body></html>" > index.html

artifacts:
  files:
    - index.html
